namePrefix: prod-
namespace: apps
commonLabels:
  env: prod

configMapGenerator:
- name: onboardingadminbot-config
  behavior: merge
  envs:
    - config.env

secretGenerator:
- name: onboardingadminbot-secret
  behavior: merge
  envs:
  - secret.env

patchesStrategicMerge:
- deployment-patch.yaml   

# patchesJson6902:
# - target:
#     group: networking.k8s.io
#     version: v1beta1
#     kind: Ingress
#     name: onboardingadminbot 
#   path: ingress-patch.yaml

resources:
- ../../base
- namespace.yaml
