namespace: onboardingadminbot

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: onboardingadminbot-config
  envs:
  - config.env

secretGenerator:
- name: onboardingadminbot-secret
  envs:
  - secret.env

resources:
- deployment.yaml

