namePrefix: dev-
namespace: apps
commonLabels:
  env: dev

configMapGenerator:
- name: onboardingadminbot-config
  behavior: merge
  envs:
    - config.env

secretGenerator:
- name: onboardingadminbot-secret
  behavior: merge
  envs:
    - secret.env

patchesStrategicMerge:
- deployment-patch.yaml    

resources:
- ../../base
- namespace.yaml
